name: asciidoctor-ghpages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # This workflow must run only under mumuki org
    if: github.repository_owner == 'mumuki'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
    - name: asciidoctor-ghpages
      uses: manoelcampos/asciidoctor-ghpages-action@v2.2.4
      with:
        # asciidoctor_params: --attribute=nofooter
        pdf_build: true
        adoc_file_ext: .adoc # default is .adoc
        pre_build: cp ./docs/README.adoc .
        # post_build: